from lfdata.video.constants import (
    CHAPTER_GETTING_READY_THRESHOLD_MS,
    CHAPTER_MULTI_NUKE_WINDOW_MS,
    CHAPTER_SPAN_THRESHOLD_MS,
    DEFAULT_AUDIO_THRESHOLD,
    DEFAULT_AUDIO_TOLERANCE_MS,
    DEFAULT_EXTRA_FOOTAGE_MS,
    DEFAULT_FADE_DURATION_S,
    DEFAULT_FPS,
    DEFAULT_FRAME_HEIGHT,
    DEFAULT_FRAME_WIDTH,
    DEFAULT_HOP_LENGTH,
    DEFAULT_HUD_MERGE_CRF,
    DEFAULT_HUD_MERGE_FADE_DURATION_MS,
    DEFAULT_HUD_MERGE_PRESET,
    DEFAULT_MAX_CHAPTERS,
    DEFAULT_N_FFT,
    DEFAULT_PREGAME_DELAY_MS,
    DEFAULT_RESOLUTION,
    DEFAULT_SAMPLE_RATE_HZ,
    MS_PER_MINUTE,
    MS_PER_SECOND,
    SECONDS_PER_MINUTE,
)


def test_video_constants():
    assert DEFAULT_FPS == 60
    assert DEFAULT_EXTRA_FOOTAGE_MS == 10000
    assert DEFAULT_PREGAME_DELAY_MS == 0
    assert DEFAULT_FADE_DURATION_S == 1.0
    assert DEFAULT_FRAME_WIDTH == 1920
    assert DEFAULT_FRAME_HEIGHT == 1080
    assert DEFAULT_RESOLUTION == (1920, 1080)


def test_time_unit_constants():
    assert MS_PER_SECOND == 1000
    assert SECONDS_PER_MINUTE == 60
    assert MS_PER_MINUTE == 60000


def test_hud_merger_constants():
    assert DEFAULT_HUD_MERGE_FADE_DURATION_MS == 5000
    assert DEFAULT_HUD_MERGE_CRF == 18
    assert DEFAULT_HUD_MERGE_PRESET == 'medium'


def test_chapter_constants():
    assert DEFAULT_MAX_CHAPTERS == 20
    assert CHAPTER_SPAN_THRESHOLD_MS == 10000
    assert CHAPTER_MULTI_NUKE_WINDOW_MS == 15000
    assert CHAPTER_GETTING_READY_THRESHOLD_MS == 20000


def test_audio_constants():
    assert DEFAULT_SAMPLE_RATE_HZ == 22050
    assert DEFAULT_HOP_LENGTH == 256
    assert DEFAULT_N_FFT == 1024
    assert DEFAULT_AUDIO_THRESHOLD == 0.2
    assert DEFAULT_AUDIO_TOLERANCE_MS == 500
