from lfdata.model.gametypes.sm5_constants import (
    DEFAULT_BOOST_GRACE_PERIOD_MS,
    DEFAULT_MISSION_PENALTY,
    SM5_BASE_CAPTURE_SCORE,
    SM5_BASE_CAPTURE_SPECIAL_POINTS,
    SM5_BASE_DESTROY_POINTS,
    SM5_BASE_DESTROY_SPECIAL_POINTS,
    SM5_BEACON_CLAIM_SHOTS_LOST,
    SM5_BOOST_AMBIGUITY_WINDOW_MS,
    SM5_BOOST_GRACE_PERIOD_MS,
    SM5_DOWNTIME_RESETTABLE_MS,
    SM5_DOWNTIME_SAFE_MS,
    SM5_DOWNTIME_TOTAL_MS,
    SM5_LIVES_LOST_MISSILED,
    SM5_LIVES_LOST_ZAPPED,
    SM5_MAX_SPECIAL_POINTS,
    SM5_NOTABILITY_ALMOST_ELIM_MAX_LIVES,
    SM5_NOTABILITY_CLOSE_GAME_MAX_DIFF,
    SM5_NOTABILITY_COMMANDER_NUKES_MIN,
    SM5_NOTABILITY_FAST_TEAM_ELIM_MAX_MS,
    SM5_NOTABILITY_HIGH_HIT_DIFF_MIN,
    SM5_NOTABILITY_HIGH_MEDIC_HITS_MIN,
    SM5_NOTABILITY_LOW_TIMES_ZAPPED_MAX,
    SM5_NOTABILITY_MEDIC_ZAPPED_MEDIC_MIN,
    SM5_NUKE_DETONATE_SCORE,
    SM5_NUKE_DETONATION_TIME_MS,
    SM5_NUKE_LIVES_LOST,
    SM5_SCORE_MISSILE_ENEMY,
    SM5_SCORE_MISSILE_TEAM,
    SM5_SCORE_MISSILED_PENALTY,
    SM5_SCORE_NUKE_DETONATE,
    SM5_SCORE_ZAP_ENEMY,
    SM5_SCORE_ZAP_TEAM,
    SM5_SCORE_ZAPPED_PENALTY,
    SM5_SPECIAL_POINTS_AMMO_BOOST,
    SM5_SPECIAL_POINTS_MEDIC_BOOST,
    SM5_SPECIAL_POINTS_MISSILE_ENEMY,
    SM5_SPECIAL_POINTS_NUKE,
    SM5_SPECIAL_POINTS_RAPID_FIRE,
    SM5_SPECIAL_POINTS_ZAP_ENEMY,
)


def test_sm5_timing_constants():
    assert SM5_DOWNTIME_TOTAL_MS == 8000
    assert SM5_DOWNTIME_SAFE_MS == 4000
    assert SM5_DOWNTIME_RESETTABLE_MS == 4000
    assert SM5_NUKE_DETONATION_TIME_MS == 10000
    assert DEFAULT_BOOST_GRACE_PERIOD_MS == 700
    assert SM5_BOOST_GRACE_PERIOD_MS == 750
    assert SM5_BOOST_AMBIGUITY_WINDOW_MS == 2000


def test_sm5_special_points_constants():
    assert SM5_MAX_SPECIAL_POINTS == 99
    assert SM5_SPECIAL_POINTS_NUKE == 20
    assert SM5_SPECIAL_POINTS_RAPID_FIRE == 15
    assert SM5_SPECIAL_POINTS_MEDIC_BOOST == 10
    assert SM5_SPECIAL_POINTS_AMMO_BOOST == 15
    assert SM5_SPECIAL_POINTS_ZAP_ENEMY == 1
    assert SM5_SPECIAL_POINTS_MISSILE_ENEMY == 2
    assert SM5_BASE_CAPTURE_SPECIAL_POINTS == 5
    assert SM5_BASE_DESTROY_SPECIAL_POINTS == 5


def test_sm5_scoring_constants():
    assert SM5_BASE_CAPTURE_SCORE == 1001
    assert SM5_BASE_DESTROY_POINTS == 1001
    assert SM5_NUKE_DETONATE_SCORE == 500
    assert SM5_SCORE_NUKE_DETONATE == 500
    assert SM5_SCORE_ZAP_ENEMY == 100
    assert SM5_SCORE_ZAP_TEAM == -100
    assert SM5_SCORE_MISSILE_ENEMY == 500
    assert SM5_SCORE_MISSILE_TEAM == -500
    assert SM5_SCORE_ZAPPED_PENALTY == -20
    assert SM5_SCORE_MISSILED_PENALTY == -100
    assert DEFAULT_MISSION_PENALTY == -1000


def test_sm5_lives_and_shots_constants():
    assert SM5_NUKE_LIVES_LOST == 3
    assert SM5_LIVES_LOST_ZAPPED == 1
    assert SM5_LIVES_LOST_MISSILED == 2
    assert SM5_BEACON_CLAIM_SHOTS_LOST == 3


def test_sm5_notability_constants():
    assert SM5_NOTABILITY_CLOSE_GAME_MAX_DIFF == 200
    assert SM5_NOTABILITY_COMMANDER_NUKES_MIN == 5
    assert SM5_NOTABILITY_HIGH_HIT_DIFF_MIN == 1.9
    assert SM5_NOTABILITY_HIGH_MEDIC_HITS_MIN == 9
    assert SM5_NOTABILITY_FAST_TEAM_ELIM_MAX_MS == 480000
    assert SM5_NOTABILITY_ALMOST_ELIM_MAX_LIVES == 5
    assert SM5_NOTABILITY_MEDIC_ZAPPED_MEDIC_MIN == 3
    assert SM5_NOTABILITY_LOW_TIMES_ZAPPED_MAX == 5
