"""CLI tool for merging GoPro base video with HUD overlay videos.

This module provides the command line interface `hudmerge` to combine a base
GoPro video with color HUD and alpha HUD mask videos generated by lfdata.

Usage example:
    # Command line:
    # hudmerge gopro.mp4 hud-color.mp4 hud-alpha.mp4 -o merged.mp4

    from lfdata.video.hudmerge import main
    main(['gopro.mp4', 'hud-color.mp4', 'hud-alpha.mp4', '-o', 'merged.mp4'])
"""

import argparse
from pathlib import Path
import sys

from lfdata.video.hud_merger import HudMerger, HudMergeOptions


def build_argument_parser() -> argparse.ArgumentParser:
    """Build the command line argument parser for hudmerge.

    Returns:
        Configured ArgumentParser instance.
    """
    parser = argparse.ArgumentParser(
        prog='hudmerge',
        description=(
            'Merge a GoPro base video with HUD color and alpha mask videos.'
        ),
    )
    parser.add_argument(
        'gopro',
        type=str,
        help='Path to the base GoPro video file.',
    )
    parser.add_argument(
        'hud',
        type=str,
        help='Path to the HUD color overlay video file.',
    )
    parser.add_argument(
        'hud_alpha',
        type=str,
        help='Path to the HUD alpha mask video file.',
    )
    parser.add_argument(
        '-o',
        '--output',
        type=str,
        default=None,
        help=(
            'Path to the output video file. Defaults to '
            '<gopro_stem>-merged.mp4.'
        ),
    )
    parser.add_argument(
        '--fade_duration_ms',
        type=int,
        default=5000,
        help='Fade out duration in milliseconds (default: 5000).',
    )
    parser.add_argument(
        '--crf',
        type=int,
        default=18,
        help='Constant Rate Factor for x264 video encoding (default: 18).',
    )
    parser.add_argument(
        '--preset',
        type=str,
        default='medium',
        help='Encoding preset for x264 (default: medium).',
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Print the FFmpeg command without executing it.',
    )
    return parser


def parse_options(args: argparse.Namespace) -> HudMergeOptions:
    """Convert parsed command-line arguments to HudMergeOptions.

    Args:
        args: Parsed command line arguments namespace.

    Returns:
        Populated HudMergeOptions dataclass.
    """
    gopro_path = Path(args.gopro)
    hud_path = Path(args.hud)
    hud_alpha_path = Path(args.hud_alpha)

    if args.output:
        output_path = Path(args.output)
    else:
        output_path = (
            gopro_path.parent / f'{gopro_path.stem}-merged{gopro_path.suffix}'
        )

    return HudMergeOptions(
        gopro_path=gopro_path,
        hud_path=hud_path,
        hud_alpha_path=hud_alpha_path,
        output_path=output_path,
        fade_duration_ms=args.fade_duration_ms,
        crf=args.crf,
        preset=args.preset,
    )


def run_merge(options: HudMergeOptions, dry_run: bool = False) -> int:
    """Execute the merge process using HudMerger.

    Args:
        options: Configuration options for the merge.
        dry_run: If True, prints the FFmpeg command instead of running it.

    Returns:
        Status exit code (0 for success, non-zero for error).

    Raises:
        RuntimeError: If probe or merge command encounters an unhandled error.
    """
    merger = HudMerger()

    if dry_run:
        gopro_meta = merger.probe_video(file_path=options.gopro_path)
        hud_meta = merger.probe_video(file_path=options.hud_path)
        cmd = merger.build_ffmpeg_command(
            options=options,
            gopro_meta=gopro_meta,
            hud_meta=hud_meta,
        )
        print('Dry run FFmpeg command:')
        print(' '.join(cmd))
        return 0

    print(f'Merging {options.gopro_path} with HUD overlays...')
    print(f'Output target: {options.output_path}')
    merger.merge(options=options)
    print(f'Successfully generated {options.output_path}')
    return 0


def main(argv: list[str] | None = None) -> int:
    """Main entrypoint for hudmerge CLI.

    Args:
        argv: Optional list of argument strings. Defaults to sys.argv[1:].

    Returns:
        Exit code (0 on success, non-zero on failure).
    """
    parser = build_argument_parser()
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])

    try:
        options = parse_options(args=args)
        return run_merge(options=options, dry_run=args.dry_run)
    except Exception as e:
        print(f'Error: {e}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
